name: Build War
on:
  push:
jobs:
  uploader:
    runs-on: ubuntu-latest
    steps:
      - name: Check out my other private repo
        uses: actions/checkout@develop
        with:
          name: ita-social-projects/TeachUAClient
          ref: refs/heads/release