name: Build War
on:
  push:
jobs:
  uploader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TeachUAClient branch
        uses: actions/checkout@v2
        with:
          repository: ita-social-projects/TeachUAClient
          ref: develop
      - name: Install dependencies
        run: "npm install"
      - name: Build frontend
        run: "CI=false npm run build"
      - name: test
        run: "ls"
      - name: test2
        run: "pwd"