name: Deploy to dev
on:
  #push:
  workflow_dispatch:
jobs:
  prcheck:
    #if: github.event.label.name == 'deploy_dev'
    runs-on: ubuntu-latest
    steps:
      - name: Create folder for frontend
        run: 'sudo mkdir /su_frontend'
      - name: Checkout frontend repo TeachUAClient
        uses: actions/checkout@v2
        with:
          repository: ita-social-projects/TeachUAClient
          ref: develop
      - name: Install dependencies
        run: "npm install"
      - name: Build frontend
        run: "CI=false npm run build"
      - name: copy frontend to frontend folder
        run: 'sudo cp -r build/* /su_frontend'
      - name: Checkout backend repo TeachUA
        uses: actions/checkout@v2
        with:
          repository: ita-social-projects/TeachUA
          ref: rest
      - name: Inject frontend
        run: 'sudo cp -r /su_frontend/* src/main/resources/frontend'     
      - name: Build war
        run: 'mvn package -DskipTests'